name: localisation-update-etl
services:
  builddata:
    image: docker-registry.ref.gnc/gouv-nc-data/gpf-geocodeur:latest
    command: bash -c "python /app/indexes/nc_build_all/index.py"
    environment:
      GEOCODE_INDEXES: address,cadastre,poi
      DEPARTEMENTS: 988
      BAN_ADDOK_URL: https://adresse.data.gouv.fr/data/ban/adresses/latest/addok/adresses-addok-{dep}.ndjson.gz
      ADDRESS_INDEX_MDB_BASE_PATH: /data/adresses/mbd_index
      ADDRESS_INDEX_PATH: /data/adresses/index
      POI_INDEX_MDB_BASE_PATH: /data/poi/mbd_index
      POI_INDEX_PATH: /data/poi/index
      BDLOC_FEATURE_SERVICE_LAYER: https://services1.arcgis.com/TZcrgU6CIbqWt9Qv/ArcGIS/rest/services/BDLOC/FeatureServer/13
      REFIL_XLSX_URL: https://data.gouv.nc/api/explore/v2.1/catalog/datasets/referentiel-des-immeubles-localises-refil/exports/xlsx
      ATLAS_FEATURE_SERVICE_LAYER: https://services1.arcgis.com/TZcrgU6CIbqWt9Qv/ArcGIS/rest/services/atlas_equipements_publics_serail/FeatureServer/0
      CAD_INDEX_MDB_BASE_PATH: /data/cadastre/mbd_index
      CAD_INDEX_PATH: /data/cadastre/index
      NC_CADASTRE_FEATURE_SERVICE_LAYER: https://services1.arcgis.com/TZcrgU6CIbqWt9Qv/arcgis/rest/services/cadastre_centroide/FeatureServer/0
      STORAGE_FS_DIR: /data
      MAGIC_TOKEN: "12345"
      HTTP_PROXY: http://proxy-for-srv.dmz.nc:3128/
      HTTPS_PROXY: http://proxy-for-srv.dmz.nc:3128/
      GLOBAL_AGENT_HTTP_PROXY: http://proxy-for-srv.dmz.nc:3128/
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.2'
    labels:
      - logweb.dtsi_access=ETUDE
